name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "*"

jobs:
  publish:
    name: "Build everything"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build everything
        run: pnpm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
