name: "Deploy Landing Page"

on: [push]
# on:
#   release:
#     types: [published]

jobs:
  publish-landing-page:
    uses: ./.github/workflows/template-deploy-to-cloudflare.yaml
    with:
      buildTarget: build:landingpage
      rootDir: ./apps/landing-page
      distDir: ./dist
      branchName: main
      cfPagesName: flethy
    secrets:
      cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
      ch_api_token: ${{ secrets.CF_API_TOKEN }}
