name: "Publish Flow"

# on: [push]
on:
  release:
    types: [published]

jobs:
  publish-flow:
    uses: ./.github/workflows/template-publish-npm-package.yaml
    with:
      packageDir: ./packages/flow
      packageScope: "@flethy/flow"
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
